GlarisEngine.UserLinkTracker/Presentation/GlarisEngine.UserLinkTracker.WebAppMVC/Models/Authentication/LoginUserViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace GlarisEngine.UserLinkTracker.WebAppMVC.Models.Authentication
{
    public class LoginUserViewModel
    {

        [Required(ErrorMessage = "The Email address field is required.")]
        [Display(Name = "Email address")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [StringLength(50, ErrorMessage = "The Email address must be at least {2} characters long.", MinimumLength = 6)]
        public string EmailAddress { get; set; }

        [Required(ErrorMessage = "The Password field is required.")]
        [StringLength(35, ErrorMessage = "The Password must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Password *")]
        public string Password { get; set; }
    }
        
}

GlarisEngine.UserLinkTracker/Presentation/GlarisEngine.UserLinkTracker.WebAppMVC/Models/Authentication/RegisterUserViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace GlarisEngine.UserLinkTracker.WebAppMVC.Models.Authentication
{
    public class RegisterUserViewModel
    {
        [Required(ErrorMessage = "The Name field is required.")]
        [Display(Name = "Your Name *")]
        [StringLength(30, ErrorMessage = "The Name must be at least {2} characters long.", MinimumLength = 6)]

        public string Name { get; set; }

        [Required(ErrorMessage = "The Email address field is required.")]
        [Display(Name = "Email address")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [StringLength(50, ErrorMessage = "The Email address must be at least {2} characters long.", MinimumLength = 6)]
        public string EmailAddress { get; set; }

        [Required(ErrorMessage = "The Password field is required.")]
        [RegularExpression(
            @"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[#$^+=!*()@%&]).{8,}$",
            ErrorMessage = @"Your password should contains a lowercase.
                           <br>Should contains a uppercase.
                           <br>Should contains a number.
                           <br>Should contains a special character(eg. ! @ # $ % &).
                           <br>Should be 8-25 characters long.")]
        [StringLength(35, ErrorMessage = "The Password must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Password *")]
        public string Password { get; set; }

        [Required(ErrorMessage = "The Confirm password field is required.")]
        [Compare("Password", ErrorMessage = "Password mismatch, Please try again.")]
        [Display(Name = "Confirm Password *")]
        public string ConfirmPassword { get; set; }

        //Range(typeof(bool), "false", "false", ErrorMessage = "Please agree with our Privacy And Security policy.")]
        public bool PrivacyAndSecurity { get; set; }

        //[Range(typeof(bool), "false", "false", ErrorMessage = "Please agree with our Terms Of Service.")]
        public bool TermsOfService { get; set; }
    }
}

GlarisEngine.UserLinkTracker/Presentation/GlarisEngine.UserLinkTracker.WebAppMVC/Models/ErrorViewModel.cs
namespace GlarisEngine.UserLinkTracker.WebAppMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GlarisEngine.UserLinkTracker/Presentation/GlarisEngine.UserLinkTracker.WebAppMVC/Controllers/AuthenticationController.cs
using AutoMapper;
using GlarisEngine.UserLinkTracker.Domain.Authentication;
using GlarisEngine.UserLinkTracker.ServiceInterface;
using GlarisEngine.UserLinkTracker.WebAppMVC.Models.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GlarisEngine.UserLinkTracker.WebAppMVC.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly ILogger<AuthenticationController> _logger;

        private readonly IAuthenticationService _authenticationService;

        private readonly IMapper _mapper;
        public AuthenticationController(ILogger<AuthenticationController> logger, IAuthenticationService authenticationService, IMapper mapper)
        {
            this._logger = logger;
            this._authenticationService = authenticationService;
            this._mapper = mapper;
        }

        [AllowAnonymous]
        [HttpGet("RegisterUser")]
        public async Task<IActionResult> GetRegisterUserAsync()
        {
            return View("RegisterUser");
        }

        [AllowAnonymous]
        [HttpPost("RegisterUser")]
        public async Task<IActionResult> RegisterUserAsync(RegisterUserViewModel registerUserViewModel)
        {
            User user = new User();
            user = this._mapper.Map<User>(registerUserViewModel);
            long userId = await this._authenticationService.RegisterUserAsync(user);
            return this.Json("User has been Created");
        }

        [AllowAnonymous]
        [HttpGet("LoginUser")]
        public async Task<IActionResult> GetLoginUserAsync()
        {
            return View("LoginUser");
        }


        [AllowAnonymous]
        [HttpPost("LoginUser")]
        public async Task<IActionResult> LoginUserAsync(LoginUserViewModel loginUserViewModel)
        {
            User user = new User();
            user = this._mapper.Map<User>(loginUserViewModel);
            UserAuthentication userAuthentication = new UserAuthentication();
            userAuthentication = await this._authenticationService.ValidateLoginUserAsync(user);
            if (userAuthentication.IsAuthentication == false)
            {
                return this.Json("User Not Found");

            }
            else
            {
                return this.Json("User has been Validated");
            }
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

GlarisEngine.UserLinkTracker/Presentation/GlarisEngine.UserLinkTracker.WebAppMVC/Controllers/HomeController.cs
using GlarisEngine.UserLinkTracker.Domain.Authentication;
using GlarisEngine.UserLinkTracker.ServiceInterface;
using GlarisEngine.UserLinkTracker.WebAppMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GlarisEngine.UserLinkTracker.WebAppMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IAuthenticationService _authenticationService;
        public HomeController(ILogger<HomeController> logger, IAuthenticationService authenticationService)
        {
            this._logger = logger;
            this._authenticationService = authenticationService;
        }

        public async Task<IActionResult> Index()
        {
            List<User> users = new List<User>();
            users = await this._authenticationService.GetAllUsersAsync();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GlarisEngine.UserLinkTracker/Presentation/GlarisEngine.UserLinkTracker.WebAppMVC/Views/Authentication/LoginUser.cshtml
@model GlarisEngine.UserLinkTracker.WebAppMVC.Models.Authentication.LoginUserViewModel

<form class="pt-3" id="formLoginUser"
      asp-controller="Authentication" asp-action="LoginUser"
      method="post" data-ajax="true"    
>
    <div id="ajaxLoginUserResult">

        <div class="mb-3">
            <label class="form-label" for="card-email">
                Email address
            </label>
            <input type="email" asp-for="EmailAddress" autocomplete="on"
                   class="form-control" id="txtLoginUserEmailAddress"
                   placeholder="Enter your email address">

            <span asp-validation-for="EmailAddress" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <div class="d-flex justify-content-between">
                <label class="form-label" for="card-password">Password</label>
                @*<a class="fs--1" href="@string.Format(_appSetting.AppURL + "ForgetPassword")"
                   title="Forget Password" id="linkForgetPassword">
                    Forgot Password?
                </a>*@
            </div>
            <input type="password" asp-for="Password" autocomplete="on"
                   class="form-control" id="txtPassword"
                   placeholder="Enter your password">
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>    
               

        <div class="mb-3">
            <button class="btn btn-primary w-100 mt-3" type="submit" id="btnSubmitLoginUser">
                Login User
            </button>

        </div>
    </div>
</form>

GlarisEngine.UserLinkTracker/Presentation/GlarisEngine.UserLinkTracker.WebAppMVC/Views/Authentication/RegisterUser.cshtml
@model GlarisEngine.UserLinkTracker.WebAppMVC.Models.Authentication.RegisterUserViewModel

<form class="pt-3" id="formRegisterUser"
      asp-controller="Authentication" asp-action="RegisterUser"
      method="post" data-ajax="true"    
>
    <div id="ajaxRegisterUserResult">

        <div class="mb-3">
            <label class="form-label" for="txtRegisterUserName">Name</label>
            <input type="text" asp-for="Name" autocomplete="username"
                   class="form-control" id="txtRegisterUserName"
                   placeholder="Enter your name">
            <span asp-validation-for="Name" class="text-danger fs--1"></span>
        </div>

        <div class="mb-3">
            <label class="form-label" for="card-email">
                Email address
            </label>
            <input type="email" asp-for="EmailAddress" autocomplete="on"
                   class="form-control" id="txtRegisterUserEmailAddress"
                   placeholder="Enter your email address">

            <span asp-validation-for="EmailAddress" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <div class="d-flex justify-content-between">
                <label class="form-label" for="card-password">Password</label>
                @*<a class="fs--1" href="@string.Format(_appSetting.AppURL + "ForgetPassword")"
                   title="Forget Password" id="linkForgetPassword">
                    Forgot Password?
                </a>*@
            </div>
            <input type="password" asp-for="Password" autocomplete="on"
                   class="form-control" id="txtCreatePassword"
                   placeholder="Enter your password">
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <div class="d-flex justify-content-between">
                <label class="form-label" for="card-password">Confirm Password</label>
                @*<a class="fs--1" href="@string.Format(_appSetting.AppURL + "ForgetPassword")"
                title="Forget Password" id="linkForgetPassword">
                Forgot Password?
                </a>*@
            </div>
            <input type="password" asp-for="ConfirmPassword" autocomplete="on"
                   class="form-control" id="txtConfirmPassword"
                   placeholder="Enter your password">
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>

        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="checkPrivacyAndSecurity"
                   asp-for="PrivacyAndSecurity">
            <label class="form-label mb-0" for="checkPrivacyAndSecurity">
                Privacy And Security
            </label>
            <span asp-validation-for="PrivacyAndSecurity" id="checkPrivacyAndSecurityVal" class="text-danger fs--1"></span>
        </div>

        <div class="form-check">
            <input class="form-check-input" type="checkbox" id="checkTermsOfService"
                   asp-for="TermsOfService">
            <label class="form-label mb-0" for="checkTermsOfService">
                Terms Of Service
            </label>
            <span asp-validation-for="TermsOfService" id="checkTermsOfServiceVal" class="text-danger fs--1"></span>
        </div>

        <div class="mb-3">
            <button class="btn btn-primary w-100 mt-3" type="submit" id="btnSubmitRegisterUser">
                Register User
            </button>

        </div>
    </div>
</form>

GlarisEngine.UserLinkTracker/Presentation/GlarisEngine.UserLinkTracker.WebAppMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GlarisEngine.UserLinkTracker/Presentation/GlarisEngine.UserLinkTracker.WebAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GlarisEngine.UserLinkTracker.WebAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GlarisEngine.UserLinkTracker.WebAppMVC.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GlarisEngine.UserLinkTracker.WebAppMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="RegisterUser">Register User</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="LoginUser">Login User</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GlarisEngine.UserLinkTracker.WebAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>